#pragma once
#include <concepts>
#include <format>
#include <string>

// Copied from: https://github.com/nathan-baggs/ufps/blob/main/src/utils/formatter.h
//
// Boost Software License - Version 1.0 - August 17th, 2003
// 
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

namespace NoctisEngine::Internal
{
 
template <class T>
concept HasToStringMember = requires(T a) {
    { a.to_string() } -> std::convertible_to<std::string>;
};

template <class T>
concept HasToStringFree = requires(T a) {
    { to_string(a) } -> std::convertible_to<std::string>;
};


struct ToStringCPO {
    template <HasToStringMember T>
    std::string operator()(T&& obj) const { return obj.to_string(); }

    template <class T>
        requires(!HasToStringMember<T> && HasToStringFree<T>)
    std::string operator()(T&& obj) const { return to_string(obj); } // ADL works
};

inline constexpr auto to_string = ToStringCPO{};

template <class T>
struct Formatter
{
    constexpr auto parse(std::format_parse_context &ctx) {
        return std::ranges::begin(ctx);
    }

    auto format(const T &obj, std::format_context &ctx) const {
        return std::format_to(ctx.out(), "{}", Internal::to_string(obj));
    }
};

} // namespace NoctisEngine::Internal

template <class T>
concept CanFormat = requires(T a) {
    { NoctisEngine::Internal::to_string(a) } -> std::convertible_to<std::string>;
};

template <CanFormat T>
struct std::formatter<T> : NoctisEngine::Internal::Formatter<T>
{};