#pragma once
#include <cstdint>
#include <unordered_map>
#include <string_view>


namespace NoctisEngine::Core
{

/// @brief This represents any physical key on your keyboard
/// @warning This is based on the QWERTY layout
enum class PhysicalKey : int
{
    KEY_SPACE       = 32,
    APOSTROPHE      = 39,
    COMMA           = 44,
    MINUS           = 45,
    PERIOD          = 46,
    SLASH           = 47,
    KEY_0           = 48,
    KEY_1           = 49,
    KEY_2           = 50,
    KEY_3           = 51,
    KEY_4           = 52,
    KEY_5           = 53,
    KEY_6           = 54,
    KEY_7           = 55,
    KEY_8           = 56,
    KEY_9           = 57,
    SEMICOLON       = 59,
    EQUAL           = 61,
    A               = 65,
    B               = 66,
    C               = 67,
    D               = 68,
    E               = 69,
    F               = 70,
    G               = 71,
    H               = 72,
    I               = 73,
    J               = 74,
    K               = 75,
    L               = 76,
    M               = 77,
    N               = 78,
    O               = 79,
    P               = 80,
    Q               = 81,
    R               = 82,
    S               = 83,
    T               = 84,
    U               = 85,
    V               = 86,
    W               = 87,
    X               = 88,
    Y               = 89,
    Z               = 90,
    LEFT_BRACKET    = 91,
    BACKSLASH       = 92,
    RIGHT_BRACKET   = 93,
    GRAVE_ACCENT    = 96,
    WORLD_1         = 161,
    WORLD_2         = 162,
    ESCAPE          = 256,
    ENTER           = 257,
    TAB             = 258,
    BACKSPACE       = 259,
    INSERT          = 260,
    DELETE          = 261,
    RIGHT           = 262,
    LEFT            = 263,
    DOWN            = 264,
    UP              = 265,
    PAGE_UP         = 266,
    PAGE_DOWN       = 267,
    HOME            = 268,
    END             = 269,
    CAPS_LOCK       = 280,
    SCROLL_LOCK     = 281,
    NUM_LOCK        = 282,
    PRINT_SCREEN    = 283,
    PAUSE           = 284,
    F1              = 290,
    F2              = 291,
    F3              = 292,
    F4              = 293,
    F5              = 294,
    F6              = 295,
    F7              = 296,
    F8              = 297,
    F9              = 298,
    F10             = 299,
    F11             = 300,
    F12             = 301,
    F13             = 302,
    F14             = 303,
    F15             = 304,
    F16             = 305,
    F17             = 306,
    F18             = 307,
    F19             = 308,
    F20             = 309,
    F21             = 310,
    F22             = 311,
    F23             = 312,
    F24             = 313,
    F25             = 314,
    NUMPAD_0        = 320,
    NUMPAD_1        = 321,
    NUMPAD_2        = 322,
    NUMPAD_3        = 323,
    NUMPAD_4        = 324,
    NUMPAD_5        = 325,
    NUMPAD_6        = 326,
    NUMPAD_7        = 327,
    NUMPAD_8        = 328,
    NUMPAD_9        = 329,
    NUMPAD_DECIMAL  = 330,
    NUMPAD_DIVIDE   = 331,
    NUMPAD_MULTIPLY = 332,
    NUMPAD_SUBTRACT = 333,
    NUMPAD_ADD      = 334,
    NUMPAD_ENTER    = 335,
    NUMPAD_EQUAL    = 336,
    LEFT_SHIFT      = 340,
    LEFT_CONTROL    = 341,
    LEFT_ALT        = 342,
    LEFT_SUPER      = 343,
    RIGHT_SHIFT     = 344,
    RIGHT_CONTROL   = 345,
    RIGHT_ALT       = 346,
    RIGHT_SUPER     = 347,
    MENU            = 348,

    MAX_KEYS,
};

/// @brief Returns the ordinal (number associated to a key) of a phyiscal key
constexpr auto ordinal(PhysicalKey key) -> int 
{
    return static_cast<int>(key);
}

/// @brief This represents the number of physcal keys the engine recognizes
constexpr int NUM_PHYSICAL_KEYS = static_cast<int>(PhysicalKey::MAX_KEYS) - 1;

static const std::unordered_map<std::string_view, PhysicalKey> KEY_NAME_MAP = 
{
    {"space",               PhysicalKey::KEY_SPACE},
    {"apostrophe",          PhysicalKey::APOSTROPHE},
    {"comma",               PhysicalKey::COMMA},
    {"minus",               PhysicalKey::MINUS},
    {"period",              PhysicalKey::PERIOD},
    {"slash",               PhysicalKey::SLASH},
    {"0",                   PhysicalKey::KEY_0},
    {"1",                   PhysicalKey::KEY_1},
    {"2",                   PhysicalKey::KEY_2},
    {"3",                   PhysicalKey::KEY_3},
    {"4",                   PhysicalKey::KEY_4},
    {"5",                   PhysicalKey::KEY_5},
    {"6",                   PhysicalKey::KEY_6},
    {"7",                   PhysicalKey::KEY_7},
    {"8",                   PhysicalKey::KEY_8},
    {"9",                   PhysicalKey::KEY_9},
    {"semicolon",           PhysicalKey::SEMICOLON},
    {"equal",               PhysicalKey::EQUAL},
    {"a",                   PhysicalKey::A},
    {"b",                   PhysicalKey::B},
    {"c",                   PhysicalKey::C},
    {"d",                   PhysicalKey::D},
    {"e",                   PhysicalKey::E},
    {"f",                   PhysicalKey::F},
    {"g",                   PhysicalKey::G},
    {"h",                   PhysicalKey::H},
    {"i",                   PhysicalKey::I},
    {"j",                   PhysicalKey::J},
    {"k",                   PhysicalKey::K},
    {"l",                   PhysicalKey::L},
    {"m",                   PhysicalKey::M},
    {"n",                   PhysicalKey::N},
    {"o",                   PhysicalKey::O},
    {"p",                   PhysicalKey::P},
    {"q",                   PhysicalKey::Q},
    {"r",                   PhysicalKey::R},
    {"s",                   PhysicalKey::S},
    {"t",                   PhysicalKey::T},
    {"u",                   PhysicalKey::U},
    {"v",                   PhysicalKey::V},
    {"w",                   PhysicalKey::W},
    {"x",                   PhysicalKey::X},
    {"y",                   PhysicalKey::Y},
    {"z",                   PhysicalKey::Z},
    {"lbracket",            PhysicalKey::LEFT_BRACKET},
    {"backslash",           PhysicalKey::BACKSLASH},
    {"rbracket",            PhysicalKey::RIGHT_BRACKET},
    {"grave",               PhysicalKey::GRAVE_ACCENT},
    {"world1",              PhysicalKey::WORLD_1},
    {"world2",              PhysicalKey::WORLD_2},
    {"esc",                 PhysicalKey::ESCAPE},
    {"enter",               PhysicalKey::ENTER},
    {"tab",                 PhysicalKey::TAB},
    {"backspace",           PhysicalKey::BACKSPACE},
    {"insert",              PhysicalKey::INSERT},
    {"delete",              PhysicalKey::DELETE},
    {"right",               PhysicalKey::RIGHT},
    {"left",                PhysicalKey::LEFT},
    {"down",                PhysicalKey::DOWN},
    {"up",                  PhysicalKey::UP},
    {"pgup",                PhysicalKey::PAGE_UP},
    {"pgdown",              PhysicalKey::PAGE_DOWN},
    {"home",                PhysicalKey::HOME},
    {"end",                 PhysicalKey::END},
    {"capslock",            PhysicalKey::CAPS_LOCK},
    {"scrolllock",          PhysicalKey::SCROLL_LOCK},
    {"numlock",             PhysicalKey::NUM_LOCK},
    {"prtsc",               PhysicalKey::PRINT_SCREEN},
    {"pause",               PhysicalKey::PAUSE},
    {"f1",                  PhysicalKey::F1},
    {"f2",                  PhysicalKey::F2},
    {"f3",                  PhysicalKey::F3},
    {"f4",                  PhysicalKey::F4},
    {"f5",                  PhysicalKey::F5},
    {"f6",                  PhysicalKey::F6},
    {"f7",                  PhysicalKey::F7},
    {"f8",                  PhysicalKey::F8},
    {"f9",                  PhysicalKey::F9},
    {"f10",                 PhysicalKey::F10},
    {"f11",                 PhysicalKey::F11},
    {"f12",                 PhysicalKey::F12},
    {"f13",                 PhysicalKey::F13},
    {"f14",                 PhysicalKey::F14},
    {"f15",                 PhysicalKey::F15},
    {"f16",                 PhysicalKey::F16},
    {"f17",                 PhysicalKey::F17},
    {"f18",                 PhysicalKey::F18},
    {"f19",                 PhysicalKey::F19},
    {"f20",                 PhysicalKey::F20},
    {"f21",                 PhysicalKey::F21},
    {"f22",                 PhysicalKey::F22},
    {"f23",                 PhysicalKey::F23},
    {"f24",                 PhysicalKey::F24},
    {"f25",                 PhysicalKey::F25},
    {"numpad_0",            PhysicalKey::NUMPAD_0},
    {"numpad_1",            PhysicalKey::NUMPAD_1},
    {"numpad_2",            PhysicalKey::NUMPAD_2},
    {"numpad_3",            PhysicalKey::NUMPAD_3},
    {"numpad_4",            PhysicalKey::NUMPAD_4},
    {"numpad_5",            PhysicalKey::NUMPAD_5},
    {"numpad_6",            PhysicalKey::NUMPAD_6},
    {"numpad_7",            PhysicalKey::NUMPAD_7},
    {"numpad_8",            PhysicalKey::NUMPAD_8},
    {"numpad_9",            PhysicalKey::NUMPAD_9},
    {"numpad_decimal",      PhysicalKey::NUMPAD_DECIMAL},
    {"numpad_divide",       PhysicalKey::NUMPAD_DIVIDE},
    {"numpad_multiply",     PhysicalKey::NUMPAD_MULTIPLY},
    {"numpad_subtract",     PhysicalKey::NUMPAD_SUBTRACT},
    {"numpad_add",          PhysicalKey::NUMPAD_ADD},
    {"numpad_enter",        PhysicalKey::NUMPAD_ENTER},
    {"numpad_equal",        PhysicalKey::NUMPAD_EQUAL},
    {"lshift",              PhysicalKey::LEFT_SHIFT},
    {"lctrl",               PhysicalKey::LEFT_CONTROL},
    {"lalt",                PhysicalKey::LEFT_ALT},
    {"lsuper",              PhysicalKey::LEFT_SUPER},
    {"rshift",              PhysicalKey::RIGHT_SHIFT},
    {"rctrl",               PhysicalKey::RIGHT_CONTROL},
    {"ralt",                PhysicalKey::RIGHT_ALT},
    {"rsuper",              PhysicalKey::RIGHT_SUPER},
    {"menu",                PhysicalKey::MENU},
};

} // namespace NoctisEngine::Input
